apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  # Upstream release
  - github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.2.0
  - workload-identity.yaml

patchesStrategicMerge:
  - application-controller.yaml
  - sa.yaml
